project:
  type: website

website:
  title: "Daniel Olofin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Publications.qmd
      - Projects.qmd
      - Training.qmd
      - updates.qmd

format:
  html:
    theme: Darkly
    css: styles.css
    toc: true

editor: visual

